name: Sync template

on:
    schedule:
        - cron: '*/5 * * * *'
    workflow_dispatch:

jobs:
    repo-sync:
        if: github.repository != 'jakezneal/alpende'
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Template Sync
              uses: AndreasAugustin/actions-template-sync@v2
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  source_repo_path: jakezneal/alpende
                  upstream_branch: main
